name: Deploy to GCP Cloud Functions

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.ts'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Restore cache node modules
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn
    - run: yarn build
    - uses: actions/upload-artifact@v2
      with:
        name: index.js
        path: index.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_CREDENTIALS }}
    - uses: actions/download-artifact@v2
      with:
        name: index.js
    - name: Deploy cloud functions
      run: gcloud functions deploy github-trends-notify --region asia-northeast1 --trigger-topic github-trends --runtime nodejs12

